---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Download 3.8 dist"
      get_url:
        url: https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz
        dest: "/tmp/Python-3.8.2.tgz"

    - name: "Unzip"
      shell: "tar -xf Python-3.8.2.tgz"
      args:
        chdir: "/tmp"

    - name: "Configure 3.8"
      shell: "./configure --prefix=/usr/local/faasm/python3.8"
      args:
        chdir: "/tmp/Python-3.8.2/"

    - name: "Install alt 3.8"
      shell: "make -j altinstall"
      args:
        chdir: "/tmp/Python-3.8.2/"

