name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    steps:
      - name: "Get the latest code"
        uses: actions/checkout@v2
      - name: "Submodules"
        run: "git submodule update --init --recursive"
      - name: "Install requirements"
        run: "pip3 install -r requirements.txt"
      - name: "Run Black"
        run: "python3 -m black --check $(git ls-files '*.py')"
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build the cpython container"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: docker/cpython.dockerfile

